---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
data("instacart")
instacart |> 
  janitor::clean_names()

# I'm interested in only the top 8 items. 
top8 = instacart |> 
  count(product_name, sort = TRUE) |> 
  slice_max(n, n = 8)

hourly_counts = instacart |> 
  filter(product_name %in% top8$product_name) |> 
  group_by(product_name, order_hour_of_day) |> 
  summarise(n = n(), .groups = "drop")

#now I want to see how long the average person goes before reordering each of these top products.
topbox = instacart |> 
  filter(product_name %in% top8$product_name)

# now lets see which on average is added first to cart

avg_add_order <- instacart |>
  filter(product_name %in% top8$product_name) |>
  group_by(product_name) |>
  summarise(mean_add_order = mean(add_to_cart_order, na.rm = TRUE)) |>
  arrange(mean_add_order)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

plot_ly(
  data = hourly_counts,
  x = ~order_hour_of_day,
  y = ~n,
  color = ~product_name,
  type = 'scatter',
  mode = 'lines'
) %>%
  layout(
    title = "Hourly Orders of Top 8 Products",
    xaxis = list(title = "Hour (0–23)"),
    yaxis = list(title = "Number of Orders"),
    legend = list(title = list(text = "Product"))
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

plot_ly(
  data = topbox,
  x = ~product_name,
  y = ~days_since_prior_order,
  type = "box",
  color = ~product_name
) %>%
  layout(
    title = "Days Since Prior Order for Top 8 Products",
    xaxis = list(title = ""),
    yaxis = list(title = "Days Since Prior Order"),
    showlegend = FALSE
  )

```

### Chart C

```{r}

plot_ly(
  data = avg_add_order,
  x = ~reorder(product_name, mean_add_order),
  y = ~mean_add_order,
  type = "bar"
) %>%
  layout(
    title = "Average Add-to-Cart Order (Top 8 Products)",
    xaxis = list(title = ""),
    yaxis = list(title = "Average Add-to-Cart Position")
  )

```

